language: java
jdk:
- oraclejdk8
install: "./gradlew clean assemble --stacktrace"
script:
- "./gradlew check --stacktrace"
after_success:
- ".buildscript/deploy_snapshot.sh"
env:
  global:
  - secure: lBIR27eM1Ko6KoCabW5+3OjACHeqTItF+nmxTrJ1jKm2SR1HdKuwEc1UgGkZK1Ykbzk/OKApf6NYNMXr+J4Znwh8g516rUiaoXXHmWHMYQbEan9QKCnQgTRmRcVWTBrt7ZJDi8GADUE0D98thN0D/AVlggyTdLqcXRptAd1TmqrccOaaqlLsQ61VyqGAQY6KcVM7gR9fbsVAp+FaOoS7shHMiWAVR4SsE+btOdXvVW/l60a7qYFQMHqkJvHaXz7aVhnqZMI3tG6Uhqy2Mpd/HfdU9/HhrpCJU1Mf846ESN/DY3Qvk3IC+C41hSKbcnusoSiNJO/Jl2iZnsg2iohcF89IOyiMsTl18rsHiqrUl8kJdu8GtlAn/BsEeQfN628i3MmZgFrS1Ta1iz3PtDGcb5tHI2B1Qsl3IWU8GF6TxdDcF5hjFguDZS/xqaFowOf/i9p+IbUMaZPvn7UHoNrnZf5uBEkWqRuDgAZHJdzjPYDST0hYAHJ74FE8svVesC4nOaWRxoE5/ynbvmBKV/LYzEbTbi5I/n5YY4nLcJWotKMBTYUa3VRlZPBcCzy/QRG9N6qVlqljENKVfaGCkhWhHY8Ze8bguIGNhtYroDwBdRKbjPBqxj0ju5nCVkKuyaxj2F0fvJPVpL2hm1yWxr8p93TL8q3O99hz0fDJsqN5KSw=
  - secure: MC7IpBcgIqfvs1Drh8yufG3AECrNcfzJUbqSWc4dGyW4cMggfefUvBsxjvTyB385jJnzywTIb1hTePXv5EFo1j4VTgnKiK0tG8eGhddLfyLLIk9/CdTe15wTmdjZFBZXk5jlxGGYajjuxcCBPoOYqyYNv6Fq/WGmXdP40pfr1eFC0AlNUW/0JLNNSMZgvW6PZR11ZyrTQj1PhryS28tnVy67VKz3GZi/7HN5+GO/xh4QJztOVog95N547PaTBN4zdKlvCYIK1fRAJYOGeYFjxRkk/H5BymipqQm84WTuEw85rszAsVeg0wc1jWMqqEY0fIZyXuIg0FapbEG8y52GXp+JI6/xwSxmixaYDQy5j236LovSQYaiZFYQnAocAOk/5ctIAKHw7Swp2BQtIxzjzHm37reiO1VW5pn+2BriTT228W2GYtAs9ICWwYSPLh+KtMfSeCguR9nLHUcLAkKzhLaS40FBxN6aT8PT2Wf1oi1euH+BAV6BmXy5SmdgvwzxM5dRPWDj2F8rcTuPYB0x5iVd+nzWu27FYAtTreGtFzOdfhCJ25ods47s7giM78sZCsZQ6L1FASGhg/LL7BkQVWjiA+w3p/QWLkXkM0k3YoMGPfxF/2Gmpb5SJwazDkCOsdXoIXLm1YzOwB2UexVu/ww5G0/iChCByNIREZeAa6c=
branches:
  except:
  - gh-pages
notifications:
  email: false
cache:
  directories:
  - "$HOME/.gradle"
